### ISSUE TITLE
How to configuration my running zookeeper server in this project

### ISSUE THREAD

**Issue by sunwenjieIT** [okapies/finagle-kafka#12]
After reading the Usage in index page. I tried but failed. IDEA console without any log info . Kafka and Zookeeper is all available. When i add this code "val zkServer = new TestingServer" at the beginning ,it  worked.This is the place where i don't understand.

**Comment by okapies** [comment]
*finagle-kafka* is just a client implemented [the Kafka protocol](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol) for Finagle and doesn't include any support for Zookeeper. It means that how to setup Kafka and Zookeeper is independent from using this library. Testing Zk Server is only required for unit testing.

**Comment by sunwenjieIT** [comment]
Thanks for answer. I already understand this code means. I know what should i do but still don't know how to replace this unit testing ZK Server code.I want some detail code or some example code if possible.Thank you.

**Comment by okapies** [comment]
TestingServer is a unit testing utility provided by curator project. See http://curator.apache.org/curator-test/ for more details.
