### ISSUE TITLE
Support ConsumerMetadataRequest available in Kafka 0.8.2

### ISSUE THREAD

**Issue by mkhq** [okapies/finagle-kafka#7]
In Kafka 0.8.2 there is an API for retrieving the offset manager for a group:

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommit/FetchAPI

This API call is used to find the broker responsible for receiving offset commit requests and to retrieve the current offset commit for a group.

In addition, there are a couple of new error codes not currently mapped:

https://cwiki.apache.org/confluence/pages/diffpagesbyversion.action?pageId=30743483&selectedPageVersions=76&selectedPageVersions=61

**Comment by mkhq** [comment]
I can try to make a pull request for these changes if its ok?

**Comment by okapies** [comment]
Welcome!

**Comment by okapies** [comment]
Resolved in #8.

**Comment by okapies** [comment]
v0.1.5 has just been published to central repo. Please let me know if there are any problems.
